import "@styles/globals.css";

import type { Metadata } from "next";
import Logo from "@assets/icons/Logo.svg";
import { Card, CardContent } from "@components/ui/card";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header>
          <div className="h-full">
            <div className="w-full h-full flex flex-col justify-center content-center flex-wrap">
              <Logo />
            </div>
          </div>
        </header>
        <nav></nav>
        <main className="flex flex-row justify-center content-center">
          <Card className="z-[1000px] absolute top-[250px] w-4/5 bg-[#1B1D1F] rounded-xl border-[#282B30]">
            <CardContent className="grid grid-cols-12 gap-4">
              {children}
            </CardContent>
          </Card>
        </main>
      </body>
    </html>
  );
}
