import "@styles/globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Image from "next/image";
import Logo from "@assets/icons/Logo.svg";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <div>
            <div className="w-full h-full flex flex-col justify-center content-center flex-wrap">
              <Logo />
            </div>
          </div>
        </header>
        <nav></nav>
        <main className="flex flex-row justify-center content-center">
          {children}
        </main>
      </body>
    </html>
  );
}
